### ISSUE TITLE
Failed to resolve au.com.ionata:tracerlib:0.1.0

### ISSUE THREAD

**Issue by mickenorlen** [ionata/TracerDemo#1]
When trying to build this project I get:

`Failed to resolve: Could not resolve au.com.ionata:tracerlib:0.1.0.`
`Could not GET 'https://packages.dev.ionata.com/artifactory/libs-release-local/au/com/ionata/tracerlib/0.1.0/tracerlib-0.1.0.pom'. Received status code 502 from server: Bad Gateway`

I also had to change:

`distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-milestone-1-all.zip`
to
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-milestone-2-all.zip`

in order to avoid:

`Unable to find method 'org.gradle.api.tasks.testing.Test.getTestClassesDirs()Lorg/gradle/api/file/FileCollection;'`

I'm trying to refactor an old project using this tracerlib dependency. Got the same error there which then lead me here. Thanks for any info on this problem.

I'm using Android Studio 3.1.2 in Linux.

**Comment by jadedarko** [comment]
Please email `support@ionata.com.au` regarding this: we do not manage issues here.

The only known user of this library is Hoodin, and we may have taken that server down if they said they were no longer using it.
